x-veld:
  code:

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/notebooks/:/veld/code/
      - ./data/storage/jupyter/:/veld/storage/jupyter/
    networks:
      - veld_postgres
    environment:
      JUPYTER_CONFIG_DIR: /veld/storage/jupyter/

networks:
  veld_postgres:
    driver: bridge

