x-veld:
  code:

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/notebooks/:/veld/code/
      - ./data/storage/jupyter/:/veld/storage/jupyter/
    environment:
      POSTGRES_HOST: null
      POSTGRES_PORT: null
      POSTGRES_DB: null
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

