x-veld:
  code:

services:
  veld_jupyter_notebook:
    build: .
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/notebooks/:/veld/code/
      - ./data/storage/jupyter/config/:/veld/storage/jupyter/config/
      - ./data/storage/jupyter/cache/:/veld/storage/jupyter/cache/
    environment:
      enable_testing: true
      table_name_sentences: null
      table_name_lemmas: null
      table_name_embeddings: null
      table_name_clusters_distances: null
      POSTGRES_HOST: null
      POSTGRES_PORT: null
      POSTGRES_DB: null
      POSTGRES_USER: null
      POSTGRES_PASSWORD: null
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

